### ISSUE TITLE
Slugify the appname in the template's _package.json

### ISSUE THREAD

**Issue by eriklharper** [akiran/generator-react-slick#1]
You should slugify the appname variable here:

https://github.com/akiran/generator-react-slick/blob/master/app/templates/_package.json#L2

It would look like this:

```
"name": "<%= _.slugify(appname) %>"
```

This will ensure that the name is properly formed without any spaces.  I got this error when running your generator initially and fixed it by changing the package.json's name to "react-slick":

```
yo react-slick

     _-----_
    |       |    .--------------------------.
    |--(o)--|    |      Welcome to the      |
   `---------´   |   incredibleReactSlick   |
    ( _´U`_ )    |        generator!        |
    /___A___\    '--------------------------'
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

   create bower.json
   create package.json
   create webpack.config.js
   create gulpfile.js
   create client/img/autumn.jpg
   create client/img/itaipu.jpg
   create client/img/lazyfonz1.png
   create client/img/lazyfonz2.png
   create client/img/lazyfonz3.png
   create client/img/lazyfonz4.png
   create client/img/lazyfonz5.png
   create client/img/lazyfonz6.png
   create client/img/mantis.png
   create client/img/new-zealand.jpg
   create client/img/river.jpg
   create client/img/sun.jpg
   create client/index.html
   create client/js/app.jsx
   create client/scss/_normalize.scss
   create client/scss/app.scss
   create .editorconfig
   create .jshintrc


I'm all done. Running bower install & npm install for you to install the required dependencies. If this fails, try running the command yourself.


bower slick-carousel#1.3.15     cached git://github.com/kenwheeler/slick.git#1.3.15
bower slick-carousel#1.3.15   validate 1.3.15 against git://github.com/kenwheeler/slick.git#1.3.15
bower jquery#>=1.7              cached git://github.com/jquery/jquery.git#2.1.3
bower jquery#>=1.7            validate 2.1.3 against git://github.com/jquery/jquery.git#>=1.7
bower slick-carousel#1.3.15    install slick-carousel#1.3.15
bower jquery#>=1.7             install jquery#2.1.3

slick-carousel#1.3.15 bower_components/slick-carousel
└── jquery#2.1.3

jquery#2.1.3 bower_components/jquery
npm ERR! install Couldn't read dependencies
npm ERR! Error: Invalid name: "react slick"
npm ERR!     at ensureValidName (/opt/boxen/nodenv/versions/v0.10.21/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:302:15)
npm ERR!     at Object.module.exports.fixNameField (/opt/boxen/nodenv/versions/v0.10.21/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:206:5)
npm ERR!     at /opt/boxen/nodenv/versions/v0.10.21/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:29:38
npm ERR!     at Array.forEach (native)
npm ERR!     at normalize (/opt/boxen/nodenv/versions/v0.10.21/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:28:15)
npm ERR!     at final (/opt/boxen/nodenv/versions/v0.10.21/lib/node_modules/npm/node_modules/read-package-json/read-json.js:328:33)
npm ERR!     at then (/opt/boxen/nodenv/versions/v0.10.21/lib/node_modules/npm/node_modules/read-package-json/read-json.js:126:33)
npm ERR!     at /opt/boxen/nodenv/versions/v0.10.21/lib/node_modules/npm/node_modules/read-package-json/read-json.js:302:48
npm ERR!     at fs.js:207:20
npm ERR!     at OpenReq.Req.done (/opt/boxen/nodenv/versions/v0.10.21/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:144:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
```

**Comment by paulwehner** [comment]
I found if the directory i tried to install the generator into had "-" in the name it created an error. if the directory was just called "project" things seem to work.
