### ISSUE TITLE
"npm start" fails - Module did not self-register...

### ISSUE THREAD

**Issue by paulwehner** [akiran/generator-react-slick#2]
After I do yo react-slick I'm trying to run npm start and I get the following output:

```
> project@1.0.1 start /Users/paulme/Google Drive/Development/Awfbeat/MVM/dev_website/react/node/starter_projects/generator-react-slick/project
> gulp

module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/paulme/Google Drive/Development/Awfbeat/MVM/dev_website/react/node/starter_projects/generator-react-slick/project/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:211:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.1
npm ERR! npm  v2.7.5
npm ERR! code ELIFECYCLE
npm ERR! project@1.0.1 start: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the project@1.0.1 start script 'gulp'.
npm ERR! This is most likely a problem with the project package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get their info via:
npm ERR!     npm owner ls project
npm ERR! There is likely additional logging output above.
```

**Comment by akiran** [comment]
Fixed this issue
